# Generated by Django 4.2 on 2023-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('yoshi', models.PositiveIntegerField(blank=True, null=True)),
                ('vazifasi', models.CharField(max_length=50)),
                ('maoshi', models.IntegerField()),
                ('bonusi', models.IntegerField()),
                ('karyera', models.IntegerField()),
                ('ish_vaqti', models.IntegerField()),
            ],
        ),
    ]
